### PR TITLE
Fix root option on glob

### PR DESCRIPTION
**Pull request by Janpot**
Fixes https://github.com/wearefractal/glob-stream/issues/37

### CODE REVIEW

**Comment by Janpot** [comment]
ok, bad test + coverage, let me fix this

**Comment by contra** [comment]
rebase?

**Comment by Janpot** [comment]
@contra done

**Comment by contra** [comment]
Needs docs on what the root option does

**Comment by Janpot** [comment]
It's already documented here: https://github.com/wearefractal/glob-stream#options

> This argument is passed directly to [node-glob](https://github.com/isaacs/node-glob#options) so check there for more options

Which leads to:

> `root` The place where patterns starting with `/` will be mounted onto. Defaults to `path.resolve(options.cwd, "/")` (`/` on Unix systems, and `C:\` or some such on Windows.)

I didn't change anything to your library, I just made it work according to your own documentation 
`¯\_(ツ)_/¯`

**Comment by Janpot** [comment]
@contra Can you give some more input on which extra docs you expect for this PR? In my opinion no extra doc is needed as this is only a bugfix on an existing feature.

**Pull request merged**
